version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:dev
    networks:
      - nestjs-app-network

networks:
  nestjs-app-network:
    driver: bridge
