version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: always
    env_file:
      - .env.production.local
    # Override environment variables
    environment:
      - NODE_ENV=production
    command: pnpm run start:prod
    networks:
      - nestjs-app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  nestjs-app-network:
    driver: bridge
